data(census)
exam<-slice(census, 1:200)
names(exam)
nrow(exam)
ncol(exam)
histogram(~Travel_time_to_school,data=exam)
range(~Travel_time_to_school,data=exam)
bargraph(~Travel_to_school,data=exam)
histogram(~Travel_time_to_school|Travel_to_school,data=exam,layout=c(1,4))
bwplot(~Travel_time_to_school|Travel_to_school,data=exam,layout=c(1,4))
MAD(~Travel_time_to_school|Travel_to_school,data=exam)
IQR(~Travel_time_to_school|Travel_to_school,data=exam)
bigfoot<-filter(exam,Footlength_cm>23)
tally(~Allergies|Vegetarian,data=exam,format="percent",margins=TRUE)

