genders<-c(male,female)
sample(cookies, size = 4, replace = TRUE)
sample(genders, size = 4, replace = TRUE)
set.seed(9)
set.seed(9)
litters2000 <- do(2000) * sample(genders, size = 4, replace = TRUE)
set.seed(9)
View(litters2000)
View(litters2000)
litters2000<-mutate(litters2000, nmale = rowSums(draws=="male"), nfemale = rowSums(draws=="female"))
set.seed(9)
litters2000<-do(2000)*sample(genders,size=4,replace= TRUE)
set.seed(9)
litters2000<-mutate(litters2000, nmale = rowSums(draws=="male"), nfemale = rowSums(draws=="female"))
new_litters2000<-mutate(litters2000, nmale = rowSums(draws=="male"), nfemale = rowSums(draws=="female"))
new_litters2000<-mutate(litters2000, nmale = rowSums(draws=="male"), nfemale = rowSums(draws=="female"))
new_litters2000<-mutate(litters2000, nmale = rowSums(litters2000=="male"), nfemale = rowSums(litters2000=="female"))
nfemale/2000
tally(~nfemale,data=new_litters2000,format="proportion")
set.seed(9)
tally(~nfemale,data=new_litters2000,format="proportion")
tally(~nmale,data=new_litters2000,format="proportion")
s", times = 48)
female <- rep("female teachers", times = 70)
male <- rep("male teachers", times = 48)
female <- rep("female teachers", times = 70)
BVN_staff <- c(male, female)
set.seed(6)
sample(BVN_staff, size = 2, replace = TRUE)
faculty1 <- do(2000) * sample(BVN_staff, size = 2, replace = TRUE)
set.seed(6)
sample(BVN_staff, size = 2, replace = TRUE)
faculty1 <- do(2000) * sample(BVN_staff, size = 2, replace = TRUE)
View(faculty1)
View(faculty1)
faculty1<-mutate(faculty1, nfemale = rowSums(faculty1=="female teachers"))
tally(~nfemale, data = faculty1)
tally(~nfemale, data = faculty1)
344/2000
344/2000
965/2000
691/2000
tally(~nfemale, data = faculty1, format = "proportion")
tally(~nfemale, data = faculty1, format = "percent")
histogram(~nfemales, data = draws_without, nint = 3)
histogram(~nfemales, data = faculty1, nint = 3)
histogram(nfemales, data = faculty1, nint = 3)
histogram(nfemales, data = faculty1, nint = 3)
set.seed(6)
male <- rep("male teachers", times = 48)
faculty1 <- do(2000) * sample(BVN_staff, size = 2, replace = TRUE)
faculty1<-mutate(faculty1, nfemale = rowSums(faculty1=="female teachers"))
histogram(nfemales, data = faculty1, nint = 3)
histogram(~nfemales, data = faculty1, nint = 3)
histogram(~nfemale, data = faculty1, nint = 3)
lotto <- c(zero, one, two, three, four, five, six, seven, eight, nine)
zero <- rep("0", times = 1)
one <- rep("1", times = 1)
two <- rep("2", times = 1)
three <- rep("3", times = 1)
four <- rep("4", times = 1)
five <- rep("5", times = 1)
six <- rep("6", times = 1)
seven <- rep("7", times = 1)
eight <- rep("8", times = 1)
nine <- rep("9", times = 1)
zero <- rep("0", times = 1)
sample(lotto, size = 1, replace = TRUE)
lotto <- c(zero, one, two, three, four, five, six, seven, eight, nine)
sample(lotto, size = 1, replace = TRUE)
sample(lotto, size = 1, replace = TRUE)
sample(lotto, size = 1, replace = TRUE)
sample(lotto, size = 3, replace = TRUE)
lotto <- c(zero, one, two, three, four, five, six, seven, eight, nine)
sample(lotto, size = 3, replace = TRUE)
set.seed(126)
Daily3 <- do(2000) * sample(lotto, size = 3, replace = TRUE)
set.seed(126)
Daily3 <- do(2000) * sample(lotto, size = 3, replace = TRUE)
View(Daily3)
win <- filter(lotto, V1=="6",V2=="1", V3=="0")
win <- filter(Daily3, V1=="6",V2=="1", V3=="0")
View(win)
View(win)
View(win)
win2 <- filter(Daily3, V1=="6",V2=="1")
win <- filter(Daily3,V2=="1", V3=="0")
win <- filter(Daily3, V1=="6",V2=="1", V3=="0")
win3 <- filter(Daily3,V2=="1", V3=="0")
win3 <- filter(Daily3,V2=="1", V3=="0")
library(readr)
babies <- read_csv("babies.csv")
View(babies)
dim(babies)
histogram(~bwt, data = babies)
histogram(~bwt, data = babies,fit = normal)
histogram(~bwt, data = babies,fit = "normal")
histogram(~bwt, data = babies,fit = "normal")
mean(~bwt, data = babies)
mean_bwt<-mean(~bwt, data = babies)
sd(~bwt,data=babies)
sd_bwt<-sd(~bwt,data=babies)
119.5769+18.23645
119.5769+18.23645+137.8133
119.5769-18.23645
119.5769-18.23645-18.23645
119.5769-18.23645-18.23645-18.23645
add_line(vline=119.57, col"brown")
add_line(vline=119.57, col="brown"")
add_line(vline=119.57, col="brown")
add_line(vline=119.57, col="brown")
add_line(vline=119.57, col="brown")
add_line(vline=137.8, col="red")
add_line(vline=101.4, col="yellow")
add_line(vline=156, col="green")
add_line(vline=83.2, col="purple")
add_line(vline=174.17, col="black")
add_line(vline=65, col="white")
add_line(vline=65, col="magenta")
one_sd_bwt<-filter(babies,bwt>101.4,bwt<137.8)
861/1236
one_sd_bwt<-filter(babies,bwt>83.2,bwt<156)
one_sd_bwt<-filter(babies,bwt>101.4,bwt<137.8)
two_sd_bwt<-filter(babies,bwt>83.2,bwt<156)
dim(two_sd_bwt)
1171/1236
pnorm(100,mean=119.6,sd=18.2)
pnorm(126.4,mean=119.6,sd=18.2)
View(atus)
View(atus)
histogram(~sleep, data = atus,breaks=seq(0, 1500,by=100) scales=list(x=list(at=seq(0, 1500,by=100))), main="Distribution of sleep in minutes",fit="normal")
histogram(~sleep, data = atus,breaks=seq(0,1500,by=100),scales=list(x=list(at=seq(0, 1500,by=100))), main="Distribution of sleep in minutes",fit="normal")
mean(~sleep,data=atus)
add_line(vline=544.57)
sd(~sleep,data=atus)
histogram(~sleep, data = atus,breaks=seq(0,550,by=50),scales=list(x=list(at=seq(0, 550,by=50))), main="Distribution of sleep in minutes",fit="normal")
histogram(~sleep, data = atus,breaks=seq(0,550,by=50),scales=list(x=list(at=seq(0, 550,by=50))), main="Distribution of sleep in minutes",fit="normal")
histogram(~sleep, data = atus,breaks=seq(0,550,by=50),main="Distribution of sleep in minutes",fit="normal")
histogram(~calories, data = food,breaks=seq(0,550,by=50),main="Distribution of scalories",fit="normal")
add_line(vline=55)
add_line(vline=calorie_mean)
add_line(vline=135.19)
sd(~calories,data=food)
load(slasher)
data("slasher")
View(slasher)
str(slasher)
tally( data = slasher, format = "percent")
tally(~gender, data = slasher, format = "percent")
tally(~gender, data = slasher)
tally(~gender, data = slasher, format = "percent")
tally(~survival, data = slasher, format = "percent")
tally(~gender|survival, data = slasher, format = "percent")
tally(~gender|survival, data = slasher)
tally(~gender|survival, data = slasher, format = "percent")
tally(~gender | survival, data = slasher, margin = TRUE)
tally(~survival | gender, data = slasher, margin = TRUE)
tally(~survival | gender, format = "percent", data = slasher, margin = TRUE)
set.seed(1)
tally(~survival | gender, data = slasher)
tally(~shuffle(survival) | gender, data = slasher)
tally(~shuffle(survival) | gender, data = slasher,format="percent")
tally(~survival|gender, data = slasher)
tally(~gender | survival, data = slasher, margin = TRUE)
tally(~survival | gender, data = slasher, margin = TRUE)
tally(~survival | gender, format = "percent", data = slasher, margin = TRUE)
set.seed(7)
shuffled_outcomes <- do(10) * tally(~shuffle(survival) | gender, format = "percent", data = slasher)
View(shuffled_outcomes)
set.seed(1)
shuffled_outcomes <- do(2000) * tally(~shuffle(survival) | gender, format = "percent", data = slasher)
set.seed(1)
shuffled_outcomes <- do(2000) * tally(~shuffle(survival) | gender, format = "percent", data = slasher)
head(shuffled_outcomes)
shuffled_outcomes <- mutate(shuffled_outcomes, diff =  Survives.Female - Survives.Male)
View(shuffled_outcomes)
histogram(shuffled_outcomes)
histogram(~shuffled_outcomes)
histogram(~difference,data=shuffled_outcomes)
histogram(~diff,data=shuffled_outcomes)
add_line(vline = 22.52252 - 13.30798)
shuffled_outcomes2 <- do(2000) * tally(~shuffle(gender) | survival, format = "percent", data = slasher)
View(shuffled_outcomes2)
head(shuffled_outcomes2)
shuffled_outcomes2 <- mutate(shuffled_outcomes2, diff =  Survives.Female - Survives.Male)
shuffled_outcomes3 <- mutate(shuffled_outcomes2, diff =  Survives.Female - Survives.Male)
shuffled_outcomes3 <- mutate(shuffled_outcomes2, diff =  Females.Survives - Males.Survives)
shuffled_outcomes3 <- mutate(shuffled_outcomes2, diff =  Female.Survives - Male.Survives)
head(shuffled_outcomes3)
set.seed(1)
shuffled_outcomes2 <- do(2000) *  tally(~survival |shuffle(gender) , format = "percent", data = slasher)
shuffled_outcomes3 <- mutate(shuffled_outcomes2, diff =  Female.Survives - Male.Survives)
shuffled_outcomes3 <- mutate(shuffled_outcomes2, diff =  Survives.Female - Survives.Male)
head(shuffled_outcomes3)
set.seed(1)
set.seed(1)
shuffled_gender<-do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
View(shuffled_gender)
head(shuffled_gender)
shuffled_gender <- mutate(shuffled_outcomes2, diff =  Survives.Female - Survives.Male)
shuffled_gender<-mutate(shuffled_gender, diff =  Survives.Female - Survives.Male)
shuffled_gender<-mutate(shuffled_gender,diff=Survives.Female-Survives.Male)
histogram(~diff,data=shuffled_gender,fit="normal")
histogram(~diff,data=shuffled_gender,fit="normal")
add_line(vline = 22.52252 - 13.30798)
data(titanic)
View(data)
View(titanic)
bwplot(~fare|survived,data=titanic,layout=c(1,4))
bwplot(~fare|survived,data=titanic,layout=c(1,2))
mean(~survived, data = titanic)
tally(~survived,data=titanic)
histogram(~fare,titanic)
histogram(~fare,titanic,main="Fare paid my Titanic Passengers")
histogram(~fare,titanic,main="Fare paid by Titanic Passengers")
histogram(~fare,data=titanic,main="Fare paid by Titanic Passengers")
data(titanic)
histogram(~fare,data=titanic,main="Fare paid by Titanic Passengers")
tally(~survived|fare,data=titanic)
mean(~fare|survived, data = titanic)
histogram(~fare|survived,data=titanic,main="Fare paid by Titanic Passengers")
stat(~fare|survived, data = titanic)
iqr(~fare|survived, data = titanic)
mean
median(~fare|survived, data = titanic)
shuffled_survival <- do(2000) * median(~fare|shuffle(survived), format = "percent", data = slasher)
shuffled_survival <- do(2000) * median(~fare|shuffle(survived), format = "percent", data = titanic)
View(shuffled_survival)
shuffled_survival <- mutate(shuffled_survival, diff =  Yes - No)
shuffled_survival <- mutate(shuffled_survival, diff =  Yes - No)
View(shuffled_survival)
View(shuffled_survival)
histogram(~diff,data=shuffled_survival)
mean(~diff|survived, data = shuffled_survival)
mean(~diff, data = shuffled_survival)
sd(~diff, data = shuffled_survival)
15.5/1.20*0.0028
1.20*0.0028/15.5
15.5-1.20/0.0028
0.0028/1.20
15.5-0.002333333
mean(~diff, data = shuffled_survival)
sd(~diff, data = shuffled_survival)
15.5-0.002333333
(15.5-0.002333333)/ 1.206557
(15.5-0.002874375)/ 1.206557
mean(~diff, data = shuffled_survival)
sd(~diff, data = shuffled_survival)
(15.5-0.002874375)/ 1.206557
First Type:  set.seed(14)
set.seed(14)
mean(~fare, data = titanic)
mean(~fare|survived, data = titanic)
bwplot(~fare|survived,data=titanic,layout=c(1,2))
shuffled_survival <- do(2000) * mean(~fare|shuffle(survived), data = titanic)
shuffled_survival <- do(2000) * mean(~fare|shuffle(survived), data = titanic)
shuffled_survival_mean <- do(2000) * mean(~fare|shuffle(survived), data = titanic)
shuffled_survival_mean <- do(2000) * mean(~fare|shuffle(survived), data = titanic)
View (shuffled_survival_mean)
shuffled_survival_mean <- mutate(shuffled_survival_mean, diff =  Yes - No)
head(shuffled_survival_mean)
histogram(~diff,data=shuffled_survival_mean, main="Differences for Shuffled Survival Mean")
library(readr)
stress <- read_csv("stress.csv")
View(stress)
dim(personalityColor)
dim(stress)
View(personalityColor)
View(personalityColor)
nrow(stress)+nrow(personalityColor)
merge(stress, personalityColor, by = "user.id")
stress_colors<-merge(stress,personalityColor,by="user.id")
View(stress_colors)
save(stress_colors, file = "stress_colors.Rda")
dotplot(~stress|p_color,data=timeuse)
dotplot(~stress|p_color,data=stress_colors)
dotPlot(~stress|p_color,data=stress_colors)
histogram(~stress|p_color,data=stress_colors)
bwplot(~stress|p_color,data=stress_colors)
library(readr)
stress_color_all <- read_csv("stress_color_all.csv")
View(stress_color_all)
histogram(~howmanypeople|p_color|int_ext,data=stress_colors)
histogram(~howmanypeople|p_color+int_ext,data=stress_colors)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_colors)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all)
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all)
histogram(~p_color|howmanypeople+int_ext,data=stress_color_all)
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all)
histogram(~p_color|howmanypeople+int_ext,data=stress_color_all)
histogram(~p_color|howmanypeople+int_ext,data=stress_color_all)
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all)
histogram(~p_color|howmanypeople+int_ext,data=stress_color_all)
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all,nint=4)
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all,nint = 4)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all,nint = 15)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all,cex=5)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all,cex=2)
dotPlot(~howmanypeople|p_color+int_ext,data=stress_color_all,cex=1)
mean(~howmanypeople|p_color+int_ext,data=stress_color_all)
median(~howmanypeople|p_color+int_ext,data=stress_color_all)
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all)
median(~howmanypeople|p_color+int_ext,data=stress_color_all)
median(~howmanypeople|p_color+int_ext,data=stress_color_all)
median(~howmanypeople|p_color+int_ext,data=stress_color_all)
mean(~howmanypeople|p_color+int_ext,data=stress_color_all)
mean(~howmanypeople|p_color+int_ext,data=stress_color_all)
mean(~howmanypeople|p_color+int_ext,data=stress_color_all)
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,color=”lightgreen”,layout=c(1,8))
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,col=”lightgreen,layout=c(1,8))
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,col="lightgreen",layout=c(1,8))
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,col="green",layout=c(1,8))
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,col="green")
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all,nint=4,col="green")
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people")
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people",col="green")
bwplot(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people",col="red")
mean(~howmanypeople|p_color+int_ext,data=stress_color_all)
median(~howmanypeople|p_color+int_ext,data=stress_color_all)
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people",col="red")
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people",col="green")
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people",col="green",nint=4)
histogram(~howmanypeople|p_color+int_ext,data=stress_color_all,main = "Relationship between primary color, people around, and introvert and extrovert", xlab = "Number of people",col="green",nint=4,type="percent")
plotDist('norm', mean = 0, sd = 1)
plotDist('norm', mean = 1, sd = 1)
plotDist('norm', mean = 2, sd = 1)
plotDist('norm', mean = 1, sd = 1)
1
plotDist('norm', mean = 2, sd = 1)
plotDist('norm', mean = 1, sd = 1)
plotDist('norm', mean = 0, sd = 1)
plotDist('norm', mean = 2, sd = 1)
plotDist('norm', mean = 1, sd = 1)
plotDist('norm', mean = 2, sd = 1)
plotDist('norm', mean = 0, sd = 2)
plotDist('norm', mean = 0, sd = 3)
plotDist('norm', mean = 0, sd = 2)
plotDist('norm', mean = 0, sd = 3)
plotDist('norm', mean = 0, sd = 3)
plotDist('norm', mean = 0, sd = 2)
plotDist('norm', mean = 0, sd = 1)
plotDist('norm', mean = 0, sd = 3)
plotDist('norm', mean = 0, sd = 2)
plotDist('norm', mean = 0, sd = 3)
data(cdc)
histogram(~height |gender,data=cdc,fit = "normal")
histogram(~height |genders,data=cdc,fit = "normal")
histogram(~weight |genders,data=cdc,fit = "normal")
histogram(~height |genders,data=cdc,fit = "normal")
histogram(~weight |genders,data=cdc,fit = "normal")
f
histogram(~height |genders,data=cdc,fit = "normal")
histogram(~height |genders,data=cdc,fit = "normal")
histogram(~height |genders,data=cdc,fit = "normal")
histogram(~weight |genders,data=cdc,fit = "normal")
do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher,fit="normal")
do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher,fit="normal")
do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
shuffled_gender<-do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
histogram(~diff,data=shuffled_gender,fit="normal")
shuffled_gender<-do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
histogram(~diff,data=shuffled_gender,fit="normal")
shuffled_gender<-do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
histogram(~diff,data=shuffled_gender,fit="normal")
View(shuffled_gender)
shuffled_gender<-do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
shuffled_outcomes <- mutate(shuffled_outcomes, diff =  Survives.Female - Survives.Male)
histogram(~diff,data=shuffled_gender,fit="normal")
shuffled_outcomes <- mutate(shuffled_outcomes, diff =  Survives.Female - Survives.Male)
histogram(~diff,data=shuffled_outcomes,fit="normal")
set.seed(1)
shuffled_gender<-do(2000)*tally(~survival|shuffle(gender),format="percent",data=slasher)
shuffled_outcomes <- mutate(shuffled_outcomes, diff =  Survives.Female - Survives.Male)
histogram(~diff,data=shuffled_outcomes,fit="normal"
set.seed(1)
set.seed(1)
shuffled_survival <- do(2000) * median(~fare|shuffle(survived), format = "percent", data = titanic)
shuffled_survival <- mutate(shuffled_survival, diff =  Yes - No)
histogram(~diff,data=shuffled_survival,fit="Normal")
d
set.seed(1)
shuffled_survival_mean <- do(2000) * mean(~fare|shuffle(survived), data = titanic)
shuffled_survival_mean <- mutate(shuffled_survival_mean, diff =  Yes - No)
histogram(~diff,data=shuffled_survival_mean,fit="Normal")
histogram(~diff,data=shuffled_survival,fit="Normal")
data(titanic)
shfls<- do(2000) * mean(~age|shuffle(survived), data = titanic)
View (shfls)
shfls <- mutate(shfls, diff =  Yes - No)
View (shfls)
mean(~diff, data = shfls)
sd(~diff, data = shfls)
View(shuffled_survival_mean)
histogram(~diff,data=shfls,fit="Normal")
mean(~age|survived, data = titanic)
add_line(vline = 30.09547 - 29.43014 )
29.43014 -30.09547
add_line(vline = -0.66533)
add_line(vline = -0.66533)
add_line(vline = -29.43014 -30.09547)
add_line(vline = 29.43014 -30.09547)
add_line(vline = 29.43014 -30.09547)
add_line(vline = -0.66533)
diff_mean<-mean(~diff, data = shfls)
diff_sd<-sd(~diff, data = shfls)
pnorm(-0.66533, mean = diff_mean, sd = diff_sd)
1 - pnorm(-0.66533, mean = diff_mean, sd = diff_sd)
set.seed(123)
draws <- rnorm(-0.66533,mean = diff_mean,sd = diff_sd)
draws <- rnorm(-0.66533, mean = diff_mean ,sd = diff_sd)
draws <- rnorm 100,mean = 67,sd = 3)
draws <- rnorm = 100,mean = 67,sd = 3)
draws <- rnorm = 100,mean = 67,sd = 3)
draws <- rnorm(100,mean = 67,sd = 3)
histogram(draws, fit = "normal")
qnorm(25, mean = 67, sd = 3)
qnorm(25%, mean = 67, sd = 3)
qnorm(25, mean = 67, sd = 3)
qnorm(0.25, mean = 67, sd = 3)
data(titanic)
shflsAgeGender<- do(2000) * mean(~age|shuffle(gender), data = titanic)
shflsAgeGender<- do(2000) * mean(~age|shuffle(genders), data = titanic)
shflsAgeGender<- do(2000) * mean(~age|shuffle(genders), data = titanic)
View (shflsAgeGender)
shflsAgeGender <- mutate(shflsAgeGender, diff =  female - male)
histogram(shflsAgeGender, fit = "normal")
histogram(diff, fit = "normal")
histogram(diff, fit = "normal")
histogram(diff, data =shflsAgeGender,  fit = "normal")
histogram(~diff,data=shflsAgeGender,fit="Normal")
shflsAgeGender <- mutate(shflsAgeGender, diff =  male - female)
histogram(~diff,data=shflsAgeGender,fit="Normal")
histogram(~diff,data=shflsAgeGender,fit="Normal")
shflsAgeGender<- do(2000) * mean(~age|shuffle(genders), data = titanic)
View (shflsAgeGender)
shflsAgeGender <- mutate(shflsAgeGender, diff =  female - male)
histogram(~diff,data=shflsAgeGender,fit="Normal")
View(titanic)
shflsAgeGender<- do(2000) * mean(~age|shuffle(sex), data = titanic)
View (shflsAgeGender)
shflsAgeGender <- mutate(shflsAgeGender, diff =  female - male)
histogram(~diff,data=shflsAgeGender,fit="Normal")
mean(~age|sex, data = shflsAgeGender)
mean(~age|sex, data = titanic)
add_line(vline = 30.47217 - 28.73145 )
pnorm(68.45,mean=80,sd=7.7)
pnorm(85,mean=80,sd=7.7)
-pnorm(85,mean=80,sd=7.7)
1-pnorm(85,mean=80,sd=7.7)
1-pnorm(95,mean=80,sd=7.7)-pnorm(2.5,mean=80,sd=7.7)
1-pnorm(80,mean=80,sd=7.7)-pnorm(95,mean=80,sd=7.7)
pnorm(80,mean=80,sd=7.7)-pnorm(95,mean=80,sd=7.7)
pnorm(95,mean=80,sd=7.7)pnorm(70,mean=80,sd=7.7)
pnorm(95,mean=80,sd=7.7)-pnorm(70,mean=80,sd=7.7)
qnorm(1.5,80,7.7)
qnorm(.15,80,7.7)
qnorm(.85,80,7.7)
pnorm(290,mean=304,sd=8)
1-pnorm(290,mean=304,sd=8)
95.9-93.5
qnorm(.90,304,8)
extra_data("hiring")
View(hiring)
View(hiring)
tally(~names|called,data=hiring)
tally(~called|names,data=hiring)
tally(~called|names,data=hiring,format="proportion")
set.seed(5)
shuffled_names<-do(2000)*tally(~called|names,data=hiring,format="proportion")
View(shuffled_names)
View(shuffled_names)
shuffled_names <- mutate(shuffled_names, diff =  yes.white - yes.black)
shuffled_names <- mutate(shuffled_names, diff =  yes.white - yes.black)
View(shuffled_names)
histogram(~diff,data=shuffled_names,fit="Normal")
View(shuffled_names)
histogram(~diff,data=shuffled_names,fit="Normal")
set.seed(5)
shuffled_names<-do(2000)*tally(~called|names,data=hiring,format="proportion")
shuffled_names <- mutate(shuffled_names, diff =  yes.white - yes.black)
histogram(~diff,data=shuffled_names,fit="Normal")
shuffled_names<-do(2000)*tally(~called|names,data=hiring,format="proportion")
set.seed(5)
shuffled_names<-do(2000)*tally(~called|names,data=hiring,format="proportion")
View(shuffled_names)
shuffled_names<-do(2000)*tally(~called|shuffle(names),data=hiring,format="proportion")
set.seed(5)
shuffled_names<-do(2000)*tally(~called|shuffle(names),data=hiring,format="proportion")
shuffled_names <- mutate(shuffled_names, diff =  yes.white - yes.black)
View(shuffled_names)
histogram(~diff,data=shuffled_names,fit="Normal")
add_line(vline = 0.034)
mean(~diff, data = shuffled_names)
sd(~diff,data=shuffled_names)
add_line(vline=0.0001791411+0.008118554,col="green")
add_line(vline=0.0001791411+2*0.008118554,col="green")
add_line(vline=0.0001791411+3*0.008118554,col="green")
add_line(vline=0.0001791411+4*0.008118554,col="green")
z <- (0.03353-.000179)/0.008118554
(0.03353-.000179)/0.008118554
1 - pnorm(0.034, 0.0001791411,0.008118554)
add_line(vline=z,col="green")
add_line(vline=4.107998,col="green")
view(titanic)
View(titanic)
library(readr)
UFC_Fights_3Rd_Decisions_Disparities <- read_csv("UFC_Fights_3Rd_Decisions_Disparities.csv")
View(UFC_Fights_3Rd_Decisions_Disparities)
savehistory("/cloud/project/rstudioCodes.r")
# reviewed: 2026-05-31 16:14:02 [3] run-29856
# reviewed: 2026-06-05 17:21:51 [5] run-26627
# reviewed: 2026-06-10 18:06:00 [7] run-6370
# reviewed: 2026-06-15 19:05:14 [9] run-20968
# reviewed: 2026-06-21 16:47:19 [2] run-7883
# reviewed: 2026-06-26 17:02:49 [4] run-21851
# reviewed: 2026-07-01 17:19:56 [6] run-4609
# reviewed: 2026-07-06 17:45:43 [8] run-24105
# reviewed: 2026-07-12 16:01:42 [1] run-20978
